name: Upload Image to AWS S3

on:
  push:
    branches:
      - main
      - master

jobs:
  convert-and-upload:
    uses: dankonscious/automation-workflow/.github/workflows/aws_deploy.yml@main
    permissions:
      contents: write
    secrets: inherit