name: Restart Workflow

on:
  issue_comment:
    types: [created]

jobs:
  restart:
    name: Restart Workflow
    if: contains(github.event.comment.body, '@restart')
    uses: EnclaveLLC/automation-workflow/.github/workflows/restart.yml@main
    with:
      issue_number: ${{ github.event.issue.number }}
      repository: ${{ github.repository }}
    secrets: inherit
    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write