name: Standard Workflow

on:
  issues:
    types: [labeled, edited]

concurrency:
  group: deploy-main
  cancel-in-progress: false

jobs:

    dispatch:
        uses: EnclaveLLC/automation-workflow/.github/workflows/standard_workflow.yml@main
        with:
            label_name: ${{ github.event.label.name }}
            issue_number: ${{ github.event.issue.number }}
        secrets: inherit
        permissions:
            contents: write
            issues: write
            pull-requests: write
